# Generated by Django 3.2.12 on 2022-04-01 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(blank=True, default='پنل ادمین جنگو', max_length=300, null=True, verbose_name='نام وب سایت')),
                ('website_logo', models.ImageField(blank=True, default='default/logo.png', null=True, upload_to='website/', validators=[django.core.validators.validate_image_file_extension], verbose_name='لوگو وب سایت')),
                ('website_favico', models.ImageField(blank=True, default='default/ico.png', null=True, upload_to='website/', validators=[django.core.validators.validate_image_file_extension], verbose_name='فیو آیکون وب سایت')),
                ('website_addr', models.URLField(blank=True, default='http://site.com', null=True, validators=[django.core.validators.URLValidator], verbose_name='آدرس وب سایت')),
                ('website_email', models.EmailField(blank=True, default='info@site.com', max_length=254, null=True, validators=[django.core.validators.EmailValidator], verbose_name='ایمیل وب سایت')),
                ('website_phone', models.CharField(blank=True, default='+98 021 123456', max_length=30, null=True, verbose_name='شماره تماس وب سایت')),
                ('terms', models.TextField(blank=True, default='قوانین استفاده از وبسایت...', null=True, verbose_name='قوانین وب سایت')),
                ('about_us', models.TextField(blank=True, default='درباره ما...', null=True, verbose_name='قوانین وب سایت')),
            ],
        ),
    ]
