# Generated by Django 3.2.12 on 2022-04-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalsetting',
            options={'verbose_name': 'تظیمات وب سایت', 'verbose_name_plural': 'تظیمات وب سایت'},
        ),
    ]
