# Generated by Django 3.2.12 on 2022-04-02 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_generalsetting_deleted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalsetting',
            options={'verbose_name': 'تظیمات کلی', 'verbose_name_plural': 'تظیمات کلی'},
        ),
    ]
