# Generated by Django 3.2.12 on 2022-04-01 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsetting',
            name='website_url',
            field=models.URLField(blank=True, default='http://site.com', null=True, validators=[django.core.validators.URLValidator], verbose_name='آدرس اینترنتی'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='about_us',
            field=models.TextField(blank=True, default='درباره ما...', null=True, verbose_name='درباره'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='terms',
            field=models.TextField(blank=True, default='قوانین استفاده از وبسایت...', null=True, verbose_name='قوانین'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='website_addr',
            field=models.CharField(blank=True, default='تهران - سید خندان - واحد 2', max_length=1000, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='website_email',
            field=models.EmailField(blank=True, default='info@site.com', max_length=254, null=True, validators=[django.core.validators.EmailValidator], verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='website_favico',
            field=models.ImageField(blank=True, default='default/ico.png', null=True, upload_to='website/', validators=[django.core.validators.validate_image_file_extension], verbose_name='فیو آیکون'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='website_logo',
            field=models.ImageField(blank=True, default='default/logo.png', null=True, upload_to='website/', validators=[django.core.validators.validate_image_file_extension], verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='website_name',
            field=models.CharField(blank=True, default='پنل ادمین جنگو', max_length=300, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='website_phone',
            field=models.CharField(blank=True, default='+98 021 123456', max_length=30, null=True, verbose_name='شماره تماس'),
        ),
    ]
