# Generated by Django 3.2.12 on 2022-04-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220401_2259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
