# Generated by Django 3.2.12 on 2022-04-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permission',
        ),
        migrations.AddField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(blank=True, to='user.Permission', verbose_name='سطح دسترسی'),
        ),
    ]
